export const colorVars = [
  "background",
  "foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "accent",
  "accent-foreground",
  "muted",
  "muted-foreground",
  "destructive",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "border",
  "input",
  "ring",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "sidebar",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-primary-foreground",
  "sidebar-accent",
  "sidebar-accent-foreground",
  "sidebar-border",
  "sidebar-ring",
]

export const grays = [
  "gray-0",
  "gray-50",
  "gray-100",
  "gray-200",
  "gray-300",
  "gray-400",
  "gray-500",
  "gray-600",
  "gray-700",
  "gray-800",
  "gray-900",
  "gray-950",
  "black",
]

export const fontSizes = [
  { label: "extra-large", var: "--font-size-h1" },
  { label: "large", var: "--font-size-h2" },
  { label: "medium-large", var: "--font-size-h3" },
  { label: "medium", var: "--font-size-h4" },
  { label: "small", var: "--font-size-h5" },
  { label: "smaller", var: "--font-size-h6" },
  { label: "default", var: "--font-size-base" },
]
